{% set name = "viridis" %}
{% set version = "0.4.2" %}
{% set sha256 = "ba8f809eb125487d919bf80c8e53e325fd3d0d7c3827179af10c54eebb12d95a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [py < 35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - networkx<2.0

test:
  requires:
    - pytest
  imports:
    - viridis.tree
  commands:
    - py.test --doctest-modules --pyargs viridis

about:
  home: https://github.com/jni/viridis
  license_family: BSD
  license: BSD 3-clause
  # Uncomment line below when license.txt is added to PyPI source dist
  # license_file: license.txt
  summary: 'A tree Python library'

  description: |
    Viridis is a Python library for tree data and algorithms. It is named
    after _Morelia viridis_, the green tree python. It is compatible with and
    tested with 100% coverage on Python 3.5.
  doc_url: https://github.com/jni/viridis
  dev_url: https://github.com/jni/viridis

extra:
  recipe-maintainers:
    - jni
