{% set version = "0.5.0" %}

package:
  name: viridis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/viridis/viridis-{{ version }}.tar.gz
  sha256: e4e65f105eaadd8ef85a90bfa66f2f5999bc55067fd35edb5cec6cbf197e0efa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - networkx <2.0

test:
  requires:
    - pytest
  imports:
    - viridis.tree
  commands:
    - pytest --doctest-modules --pyargs viridis

about:
  home: https://github.com/jni/viridis
  license_family: BSD
  license: BSD-3-Clause
  # Uncomment line below when license.txt is added to PyPI source dist
  # license_file: license.txt
  summary: A tree Python library

  description: |
    Viridis is a Python library for tree data and algorithms. It is named
    after _Morelia viridis_, the green tree python. It is compatible with and
    tested with 100% coverage on Python 3.5.
  doc_url: https://github.com/jni/viridis
  dev_url: https://github.com/jni/viridis

extra:
  recipe-maintainers:
    - jni
