travis:
  secure:
    BINSTAR_TOKEN: qeT5tP+Q6DE483UnUqlfFHSlfNptTefvhiThOziBbLPVvJUZF3KLlPy77VV2R9cMuc+mkX7Bar7f2aKX001/znFs0oBFmyCRBW0aP+DBvfohKd6HwMc/Fa97icAkmRcgFkPheMXWiSpAvQ5Zao+OKc7VGF24Ub2AbLH5xy3zz1SwVoPxfxerkaHqZIyLmPJRf0urJc6P15AnL97Ba+WCAZiqZqZ0JBuY5mS8RArddKfIUjfWh3oyFmZWpDSzGW11go1P/m4hp1/3kX75+wwJZISDxJ/strN5QjnwSCR64xs5Bu69IABeEAnHC6NeiNnqHVZZl1k7S5K81Phu7qFTKy+UBfeNXCQZo2vtRkzPvQB3mTr3gfiO6TaqEW1NDTok5r7g4AYPVlC53uJrXD7l0sFENfdq/mNsIcvlO++rf6tkkZoXND7+Le40VN5iMc16g/D43EDcGz1PBvZkCz29NuowNgT2GTIFD9eFjKZaOwUB6SiiqMTcB7gvBnbN6nJFmHinHakRMCsX1TOIttMqjEQ53wNBkHU4kuBt9macvfbcW2ByhcBCTcmh4kTpw7i9LD1XDfO1nj4UvaDs4wdUMN8nm+jid2Fv8C2tI0dgshlMbCMasQhKkyunbfCeaUXdARWxp7INaS0T79VtMB5rn38ynZB//pMz43EEz8Oi80c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
