travis:
  secure:
    BINSTAR_TOKEN: WR1/L9xnrb4inQqzS81UbvGL1pca3uEuNUvkqrX3V3PqyvXCf3P71SJ3/UZJdfyzLKVCRPdiHs47LbW2EoAg7xDbTVporWbjbfS0NasWNF2vlKB+G5t8lkdA5YI2ooWWg8/UMD7gJwuCllDqbQtN2Gs243FsJ5xaEYmHN1lIrsmSfbuRJGVbOwuRUVWYTuJMUP8vqGvLgEZlWSgJHuF+MQ5+1SVDZ8EwT59KSsH4vNmhZvlaVFnXgX/ymdIq4ufJslOuLWPPNk1Si4Fdrs8NRpmKDG25xJNWj289fiMvknqGcIFBD8g5jiYrPR7VTjx726Buaqp1eS2oznVeNUc+AXM50hTj2MJEoC4KO1yCE7tIi1bz34q8CAvXADa6di0JyILbiKWk7jYQslxtiShrw5QCwr2JoASQ8y+ckt+hAqQHzRelCHh2LGz8zULKcPK1yRgul18eR7+abYUJDAG18EP59jVgJZpuRqmOiN6OmOupsNl8Rb5cQhtaMvuJSE3sMRfmfau0pqwqt/Xay5MfwcFuegdEKaOMgpI1cKywCW02ba6QkdJevuCk3pRvtt+QJ7FntGUttLLL/e7QqTRLA1tyH+qUSrQKvxMfSc8ojnLyvffpqn6EC8CdvY252GVYjevAWo0vmgJqlYOXran0GO6dGM9DKbjPBOyXGfSfGQM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
